.TH pk 1 "January 19, 2010" "EasyPK 2.3"
.SH NAME
pk \- PacK script
.SH SYNOPSIS
.B pk -h|tar|tbz|tgz|bz2|gz|7z|zip|rar [-d] [-o
.I 
outfile
.B
]
.I
file
.B ...
.SH DESCRIPTION
.B pk
is a part of EasyPK package which aimed to simplify archives handling. pk gives you unified interface for creating tar, gzip, bzip2, zip, 7zip and rar archives.
.P
.B
pk
uses
.BR pv (1)
utility to show nice progress bars while creating archives, but it will work without pv too.
.SH OPTIONS
.TP
.B \-h
Disply a short help
.TP
.B tar, tbz, tbz2, tgz, bz2, gz, 7z, zip, rar
Resulting archive format
.TP
.B \-d
Delete input files after adding them to archive
.TP
.BI \-o " outfile"
Use
.I
outfile
as output file
.SH EXIT STATUS
Exit status is normally 0; if an error occurs,
.B
pk
returns number of error. See
.B
ERRORS
for details.
.SH ERRORS
.TP
.B 0
No errors occurred.
.TP
.B 1
Archive format not specified.
.TP
.B 2
Input files not specified.
.SH BUGS
There are some certainly. If you found one, please mail the author (see
.B
AUTHOR
section for details).
.SH EXAMPLES
.TP
.B pk tar -o /tmp/backup.tar ~/documents ~/photos
Create backup of your documents and photos
.TP
.B pk tbz -d logs
Create compressed archive with your logs and delete input files.
.SH AUTHOR
The author of this software is Alexander Batischev.
You can mail him about EasyPK at <\fIeual.jp@gmail.com\fR>
.SH SEE ALSO
.BR atool (1),
.BR bzip2 (1),
.BR gzip (1),
.BR pv (1),
.BR rar (1)
.BR tar (1),
.BR 7z (1)

